"Name: \TY:CL_HRPA_OM_INTEGRATION\ME:ENABLE_OM_INTEGRATION\SE:BEGIN\EI
ENHANCEMENT 0 /SEW/HCM_ORALCE_INT_PAOM_INT.
IF sy-cprog = '/SEW/RP_IT_AEND_POST'.
  GET PARAMETER ID 'HC' FIELD DATA(global_hc).
  IF global_hc = abap_false.
  EXIT.
  ENDIF.
ENDIF.
ENDENHANCEMENT.
